# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Radar < Formula
  desc "Modern Kubernetes visibility — topology, traffic, and Helm management"
  homepage "https://github.com/skyhook-io/radar"
  version "0.7.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyhook-io/radar/releases/download/v0.7.1/radar_v0.7.1_darwin_amd64.tar.gz"
      sha256 "c7d389ac182a6e6582a2af7b62023c4a090e8a335a9d22f5af010f8c7f0ad630"

      def install
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyhook-io/radar/releases/download/v0.7.1/radar_v0.7.1_darwin_arm64.tar.gz"
      sha256 "031f5fd0716fadbe4239de8523bd8d6807bfeb2678c2e80ff0f01ab0b0b45bd9"

      def install
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/radar/releases/download/v0.7.1/radar_v0.7.1_linux_amd64.tar.gz"
      sha256 "0f81fdcf22f965e1d5954357869b1c0bde65d6d12dd506c3a3f84df270caf78f"
      def install
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/radar/releases/download/v0.7.1/radar_v0.7.1_linux_arm64.tar.gz"
      sha256 "9c4284558e738da1fc3cfd320de6527ecde56ba65cc82267498f3d552c7add0b"
      def install
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
  end

  test do
    system "#{bin}/kubectl-radar", "--version"
  end
end
