# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Radar < Formula
  desc "Modern Kubernetes visibility — topology, traffic, and Helm management"
  homepage "https://github.com/skyhook-io/radar"
  version "1.8.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyhook-io/radar/releases/download/v1.8.4/radar_v1.8.4_darwin_amd64.tar.gz"
      sha256 "c4c13aaccf4947552db039cebaa28765c69194846fc39439c5c0ebafcfaf5e7e"

      define_method(:install) do
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyhook-io/radar/releases/download/v1.8.4/radar_v1.8.4_darwin_arm64.tar.gz"
      sha256 "cf4a2fec6122af3cede3e86733c7361b16516e77dde48dfce00851679b012f19"

      define_method(:install) do
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/radar/releases/download/v1.8.4/radar_v1.8.4_linux_amd64.tar.gz"
      sha256 "2d48dd806e076f144210c3f60e1c563f3608a4aa8844e2bb544c4adf7406083c"
      define_method(:install) do
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/radar/releases/download/v1.8.4/radar_v1.8.4_linux_arm64.tar.gz"
      sha256 "724346945b8b5f112c49481fe3ec244d05dd96afba225ed7f13c299837458541"
      define_method(:install) do
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
  end

  test do
    system "#{bin}/kubectl-radar", "--version"
  end
end
