# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Radar < Formula
  desc "Modern Kubernetes visibility — topology, traffic, and Helm management"
  homepage "https://github.com/skyhook-io/radar"
  version "0.9.14"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skyhook-io/radar/releases/download/v0.9.14/radar_v0.9.14_darwin_amd64.tar.gz"
      sha256 "3acd6c1c9fbc3a42b36a707e17a2e7338a314e3765c496ffb0e32ad13c57195d"

      def install
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skyhook-io/radar/releases/download/v0.9.14/radar_v0.9.14_darwin_arm64.tar.gz"
      sha256 "4e507586ab5a1db95c8e5ec293def6e77cd180a2ce2f08f9db85ab7d9b8b33c6"

      def install
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/radar/releases/download/v0.9.14/radar_v0.9.14_linux_amd64.tar.gz"
      sha256 "89712b4bb331f6bcf140de9e7e44abc973eb97aadf15e2cd58e1b3d7d73e8b3e"
      def install
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skyhook-io/radar/releases/download/v0.9.14/radar_v0.9.14_linux_arm64.tar.gz"
      sha256 "a31f63fe61eb8d4d8a7a5e3b50378f6ce1b6ea88e1481cbae099e8453a6c52d3"
      def install
        bin.install "kubectl-radar"
        bin.install_symlink "kubectl-radar" => "radar"
      end
    end
  end

  test do
    system "#{bin}/kubectl-radar", "--version"
  end
end
